name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install root dependencies
      run: npm ci

    - name: Install client dependencies
      run: |
        cd client
        npm ci

    - name: Run backend tests
      run: npm test

    - name: Run frontend tests
      run: |
        cd client
        npm test -- --run

    - name: Build application
      run: npm run build

    - name: Test production build
      run: |
        # Start server in background
        npm start &
        SERVER_PID=$!
        
        # Wait for server to start
        sleep 5
        
        # Test that server responds
        curl -f http://localhost:4000/api/health || exit 1
        
        # Cleanup
        kill $SERVER_PID

  # Optional: Deploy to staging on main branch
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - name: Deploy to production
  #     run: |
  #       # Add your deployment commands here
  #       # Examples: Railway, Render, Heroku deployment
  #       echo "Deploy to production server"